#!/bin/sh

# errors shouldn't cause script to exit
set +e

pyrcc5 -o /opt/qml4cop/images_rc.py /opt/qml4cop/images.qrc

INIT_SYSTEM=`cat /proc/1/comm`
if test $INIT_SYSTEM = "systemd"
then
        systemctl daemon-reload
        systemctl enable qml4cop.service 2>/dev/null
        systemctl start qml4cop.service 2>/dev/null
fi
exit 0
